"""Code generation — turns wizard state into tool_implementation.py +
tool_config.json contents. Two strategies:

  - templates(...) — Jinja2 templates per tool kind (file_reader, sql,
    rest, rag). Deterministic, no network call. Used when the user
    picks a canned kind in step 5.

  - llm_assisted(...) — defers to llm_client.generate_tool_code. Used
    when the user picks "custom (LLM-generated)" or wants free-form
    behavior. The LLM produces tool_implementation.py; we still
    generate tool_config.json from state.
"""

from __future__ import annotations

import json
from typing import Tuple


HELPERS_SUMMARY = """\
- aidp_io.read_text(uri, conf, ctx) / write_text(uri, str, conf, ctx) — read or
  write strings against AIDP master:cat.sch.vol:/path or workspace:/path URIs.
- aidp_io.read_file / write_file — bytes variant for binary files.
- aidp_io.list_files(uri, conf, ctx) — list a folder URI.
- aidp_io.resolve_catalog / resolve_schema / resolve_volume / resolve_kb /
  resolve_table — fuzzy name resolvers (prefix / substring tolerant).
- aidp_genai.chat(prompt, conf, model_id=..., system=..., max_tokens=...) — OCI
  GenAI chat. aidp_genai.embed(texts, conf, ...) — embeddings.
- aidp_kb.kb_search(query, kb_key, conf, top_k=5) — RAG search against an
  AIDP knowledge base.
- aidp_session.resolve_session_variable_references(value, session) — replace
  {{var}} placeholders from a session dict.
- aidputils.secrets.get(name, key=None) — resolve an AIDP Credential Store
  entry by display name. For OCI API-key auth: create a SECRET_TOKEN
  credential with keys tenancy/user/fingerprint/private_key, then call
  secrets.get(name) to get the full bundle. See
  CUSTOM_CODE_TOOLS/credential_store_auth_sample for the full pattern.
"""


# ---------------------------------------------------------------------------
# tool_config.json synthesizer (used by both strategies)
# ---------------------------------------------------------------------------

def build_tool_config(state) -> str:
    """Compose a tool_config.json from wizard state. The schema fields
    come from the picked tool_kind; conf carries the standard AIDP +
    auth fields with the wizard's resolved values pre-filled."""
    schema = _schema_for_kind(state.tool_kind, state)
    config = {
        "displayName": state.tool_display_name or state.tool_class_name,
        "description": state.tool_description or "Generated by AIDP Tool Wizard.",
        "tools": [{
            "toolClassName": state.tool_class_name,
            "displayName": state.tool_display_name or state.tool_class_name,
            "description": state.tool_description or "Generated by AIDP Tool Wizard.",
            "version": "1.0.0",
            "schema": schema,
            "conf": {
                "region": state.region,
                "data_lake_ocid": state.data_lake_ocid,
                "api_version": "20260430",
                "service_path": "aiDataPlatforms",
                "auth_mode": "auto",
                "timeout": 30,
                # AIDP Credential Store reference (Jun-26 JR/Sambit guidance).
                # Operator creates a SECRET_TOKEN credential with keys
                # tenancy/user/fingerprint/private_key; the tool resolves it
                # via aidputils.secrets.get(name) at invoke time. Leave empty
                # to fall back to resource principal (will 401 against public
                # AIDP data-plane endpoints — kept only for AIDP-internal use).
                "credential_name": "",
                # Resource defaults — the LLM-generated code can read these.
                "catalog": state.catalog_name,
                "schema": state.schema_name,
                "volume": state.volume_name,
                "volume_key": state.volume_key,
                "kb_key": state.kb_key,
            },
            "auth": {"authType": "OCI_RESOURCE_PRINCIPAL"},
            "_uiHints": {
                "conf": {
                    "region":          {"kind": "dropdown", "source": "regions"},
                    "data_lake_ocid":  {"kind": "dropdown", "source": "dataLakes"},
                    "catalog":         {"kind": "dropdown", "source": "catalogs"},
                    "schema":          {"kind": "dropdown", "source": "schemas", "dependsOn": "catalog"},
                    "volume":          {"kind": "dropdown", "source": "volumes", "dependsOn": "schema"},
                    "auth_mode":       {"kind": "enum", "values": ["auto", "resource_principal", "session_token", "user_principal"]},
                    "credential_name": {"kind": "input", "inputStyle": "singleline",
                                        "help": "Display name of a SECRET_TOKEN credential in AIDP's Credential Store. Required for public AIDP data-plane calls (resource principal returns 401)."},
                },
                "schema": {},
            },
        }],
    }
    return json.dumps(config, indent=2) + "\n"


def _schema_for_kind(kind: str, state) -> list:
    """Per-kind runtime parameter schema."""
    if kind == "file_reader":
        return [
            {"name": "path", "type": "string",
             "description": "File path within the volume, e.g. /docs/manual.pdf.",
             "examples": ["/docs/safety_manual.pdf", "/reports/q3.csv"]},
        ]
    if kind == "sql":
        return [
            {"name": "query", "type": "string",
             "description": "SQL query string. Use {{param}} placeholders.",
             "examples": ["SELECT count(*) FROM employees WHERE dept = {{dept}}"]},
        ]
    if kind == "rest":
        return [
            {"name": "method", "type": "string", "enum": ["GET", "POST", "PUT", "DELETE"],
             "default": "GET"},
            {"name": "url", "type": "string", "description": "Full URL."},
            {"name": "body", "type": "string", "description": "Optional JSON body."},
        ]
    if kind == "rag":
        return [
            {"name": "query", "type": "string",
             "description": "Natural-language search query."},
            {"name": "top_k", "type": "number", "default": 5},
        ]
    # llm_custom or anything else
    return [
        {"name": "input", "type": "string",
         "description": "Free-form input the LLM-generated tool consumes."},
    ]


# ---------------------------------------------------------------------------
# Template-based implementation strategy (no network call)
# ---------------------------------------------------------------------------

def template_implementation(state) -> str:
    """Render a tool_implementation.py from a canned template for the
    picked kind. Used when the user didn't ask for LLM-assisted gen."""
    cls = state.tool_class_name
    if state.tool_kind == "file_reader":
        return _FILE_READER_TEMPLATE.format(cls=cls, desc=state.tool_description)
    if state.tool_kind == "sql":
        return _SQL_TEMPLATE.format(cls=cls, desc=state.tool_description)
    if state.tool_kind == "rest":
        return _REST_TEMPLATE.format(cls=cls, desc=state.tool_description)
    if state.tool_kind == "rag":
        return _RAG_TEMPLATE.format(cls=cls, desc=state.tool_description)
    # Fallback for llm_custom — emit a stub that just echoes input.
    return _ECHO_STUB.format(cls=cls, desc=state.tool_description)


# ---------------------------------------------------------------------------
# LLM-assisted implementation
# ---------------------------------------------------------------------------

def llm_implementation(state) -> Tuple[str, str]:
    """Call the configured LLM provider. Returns (code, error_msg).
    On success, error_msg is empty."""
    from .llm_client import generate_tool_code
    context = {
        "Region": state.region,
        "Workspace": f"{state.workspace_name} ({state.workspace_key})",
        "Catalog": f"{state.catalog_name} ({state.catalog_key})" if state.catalog_name else "",
        "Schema": f"{state.schema_name} ({state.schema_key})" if state.schema_name else "",
        "Volume": f"{state.volume_name} ({state.volume_key})" if state.volume_name else "",
        "Knowledge base": f"{state.kb_name} ({state.kb_key})" if state.kb_name else "",
        "Tool kind hint": state.tool_kind,
    }
    code, err = generate_tool_code(
        state.llm_provider, state.llm_api_key, state.llm_model,
        user_intent=state.user_intent,
        tool_class_name=state.tool_class_name,
        aidp_context=context,
        helpers_summary=HELPERS_SUMMARY,
    )
    return (code or "", err or "")


# ---------------------------------------------------------------------------
# Validators run on every generated implementation
# ---------------------------------------------------------------------------

def validate_implementation(code: str, expected_class: str) -> Tuple[bool, str]:
    """Quick AST + content checks before letting the user move on."""
    import ast
    if not code.strip():
        return False, "Empty implementation."
    try:
        tree = ast.parse(code)
    except SyntaxError as e:
        return False, f"SyntaxError: {e.msg} (line {e.lineno})"
    found_class = False
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name == expected_class:
            found_class = True
            break
    if not found_class:
        return False, f"No class named `{expected_class}` defined."
    if "_execute_tool" not in code:
        return False, "Class is missing the required `_execute_tool` method."
    if "@CustomToolBase.register" not in code and "@BaseTool.register" not in code:
        return False, "Class isn't decorated with @CustomToolBase.register."
    return True, "Implementation looks valid."


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

_COMMON_PREAMBLE = '''"""{desc}

Generated by AIDP Tool Wizard.
"""

from typing import Any, Dict

from aidputils.agents.tools.custom_tools.base import CustomToolBase
from .utils.config_utils import get_cfg, ok, fail

try:
    from aidp_debug import debug, debug_warn, debug_error, DebugLog
except ImportError:
    def debug(*a, **k): pass
    def debug_warn(*a, **k): pass
    def debug_error(*a, **k): pass
    class DebugLog:
        @staticmethod
        def embed(r): return r
'''


_FILE_READER_TEMPLATE = _COMMON_PREAMBLE + '''

@CustomToolBase.register
class {cls}(CustomToolBase):
    """Read a file from the AIDP volume the wizard pre-configured."""

    @classmethod
    def _execute_tool(cls, conf: Dict[str, Any], runtime_params: Dict[str, Any],
                      **context_vars) -> Dict[str, Any]:
        debug("{cls}._execute_tool start")
        try:
            from .utils.aidp_io import read_text
            path = runtime_params.get("path", "")
            if not path:
                return fail("`path` is required", "ValidationError")
            volume_key = get_cfg(conf, "volume_key", "")
            if not volume_key:
                return fail("conf.volume_key not set — re-run the wizard or set manually",
                            "ValidationError")
            uri = f"master:{{volume_key}}:{{path}}"
            content = read_text(uri, conf, context_vars)
            return DebugLog.embed(ok({{"path": path, "content": content,
                                        "bytes": len(content.encode('utf-8'))}}))
        except Exception as e:
            return DebugLog.embed(fail(str(e), type(e).__name__))
'''


_SQL_TEMPLATE = _COMMON_PREAMBLE + '''

@CustomToolBase.register
class {cls}(CustomToolBase):
    """Run a parameterized SQL query against the catalog the wizard pre-configured.
    Note: For non-trivial SQL, prefer AIDP's first-party SQL tool. This is a
    minimal scaffold for tools that wrap one specific query."""

    @classmethod
    def _execute_tool(cls, conf: Dict[str, Any], runtime_params: Dict[str, Any],
                      **context_vars) -> Dict[str, Any]:
        debug("{cls}._execute_tool start")
        try:
            from .utils.aidp_io import get_external_catalog_connection
            query = runtime_params.get("query", "")
            if not query:
                return fail("`query` is required", "ValidationError")
            conn_info = get_external_catalog_connection(
                get_cfg(conf, "catalog_key", "") or get_cfg(conf, "catalog", ""),
                conf, context_vars,
            )
            # NOTE: implementation of the query execution depends on
            # whether the catalog is Oracle / Spark — wire up oracledb or
            # pyspark here based on conn_info['type'].
            return DebugLog.embed(ok({{"connection": conn_info["type"],
                                        "query": query,
                                        "TODO": "wire up oracledb cursor here"}}))
        except Exception as e:
            return DebugLog.embed(fail(str(e), type(e).__name__))
'''


_REST_TEMPLATE = _COMMON_PREAMBLE + '''
import requests


@CustomToolBase.register
class {cls}(CustomToolBase):
    """Call an external REST endpoint."""

    @classmethod
    def _execute_tool(cls, conf: Dict[str, Any], runtime_params: Dict[str, Any],
                      **context_vars) -> Dict[str, Any]:
        debug("{cls}._execute_tool start")
        try:
            method = (runtime_params.get("method") or "GET").upper()
            url = runtime_params.get("url", "")
            body = runtime_params.get("body", "")
            timeout = get_cfg(conf, "timeout", 30)
            if not url:
                return fail("`url` is required", "ValidationError")
            kwargs = {{"timeout": timeout}}
            if body:
                kwargs["data"] = body
            r = requests.request(method, url, **kwargs)
            r.raise_for_status()
            ct = r.headers.get("Content-Type", "")
            payload = r.json() if "json" in ct else r.text[:64000]
            return DebugLog.embed(ok({{"status": r.status_code, "body": payload}}))
        except Exception as e:
            return DebugLog.embed(fail(str(e), type(e).__name__))
'''


_RAG_TEMPLATE = _COMMON_PREAMBLE + '''

@CustomToolBase.register
class {cls}(CustomToolBase):
    """Search an AIDP Knowledge Base."""

    @classmethod
    def _execute_tool(cls, conf: Dict[str, Any], runtime_params: Dict[str, Any],
                      **context_vars) -> Dict[str, Any]:
        debug("{cls}._execute_tool start")
        try:
            from .utils.aidp_kb import kb_search
            query = runtime_params.get("query", "")
            top_k = int(runtime_params.get("top_k", 5))
            kb_key = get_cfg(conf, "kb_key", "")
            if not query or not kb_key:
                return fail("`query` and conf.kb_key are both required",
                            "ValidationError")
            hits = kb_search(query, kb_key, conf, top_k=top_k,
                             context_vars=context_vars)
            return DebugLog.embed(ok({{"query": query, "top_k": top_k,
                                        "hits": hits, "count": len(hits)}}))
        except Exception as e:
            return DebugLog.embed(fail(str(e), type(e).__name__))
'''


_ECHO_STUB = _COMMON_PREAMBLE + '''

@CustomToolBase.register
class {cls}(CustomToolBase):
    """Stub generated when no LLM was used. Replace _execute_tool with your logic."""

    @classmethod
    def _execute_tool(cls, conf: Dict[str, Any], runtime_params: Dict[str, Any],
                      **context_vars) -> Dict[str, Any]:
        debug("{cls}._execute_tool start")
        try:
            payload = runtime_params.get("input", "")
            return DebugLog.embed(ok({{"echo": payload}}))
        except Exception as e:
            return DebugLog.embed(fail(str(e), type(e).__name__))
'''
