#!/usr/bin/env python3
"""One-shot script that generates the catalog JSON for the remaining 13 KB
methods from a structured Python representation of the Confluence rows.

The Confluence text was reviewed row-by-row and each (scenario, expected
message) pair was classified. The output is a JSON file per method that
the harness can consume.

Re-run this when AIDP updates the message catalog and you want to refresh
the JSON files from the structured source.
"""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent

# Common substrings — reused across methods so the harness can match.
SUB_INVALID_PARAM = "Invalid request. The parameter"
SUB_INVALID_GENERIC = "Invalid request. Some required fields are missing or invalid."
SUB_FEATURE_CFG = "Service unavailable. Unable to read Knowledge Base feature configuration"
SUB_FEATURE_OFF = "Knowledge Base not enabled."
SUB_CLUSTER_DOWN = "Service unavailable. The default cluster is currently unavailable."
SUB_EMBEDDING = "Embedding model is not found."
SUB_DB_TIMEOUT = "Database connection timed out."
SUB_DB_FAIL = "Database connection failed."
SUB_DB_RES = "Database resources unavailable."
SUB_DB_OP = "Database operation failed."
SUB_NOT_FOUND_KB = "Not found. The requested Knowledge Base"
SUB_NOT_FOUND_JOB = "Not found. The requested Knowledge Base job"
SUB_NOT_FOUND_RUN = "Not found. The requested Knowledge Base job run"

def infra(method, scenario, msg):
    return {"method": method, "scenario": scenario, "class": "infra",
            "skip_reason": "AIDP-side state.",
            "expected_message_substring": msg}

def dbinject(method, scenario, msg):
    return {"method": method, "scenario": scenario, "class": "db_inject",
            "skip_reason": "Requires DB-level fault injection.",
            "expected_message_substring": msg}

def race(method, scenario, msg):
    return {"method": method, "scenario": scenario, "class": "race",
            "skip_reason": "Timing-dependent.",
            "expected_message_substring": msg}

def noop(method, scenario, note=None):
    out = {"method": method, "scenario": scenario, "class": "noop",
           "expected_status": [200, 201, 202, 204]}
    if note:
        out["notes"] = note
    return out

def fixture_not_found(method, scenario, path_template, msg, kb_path="kb_does_not_exist"):
    return {"method": method, "scenario": scenario, "class": "fixture",
            "fixture_required": "request_nonexistent_kb",
            "verb": method_verb(method),
            "path_template": path_template,
            "variants": [{"name": "nonexistent target",
                          "path_params": {"kb_key": kb_path}}],
            "expected_status": [404],
            "expected_message_substring": msg}

def validation(method, scenario, verb, path_template, variants, msg=SUB_INVALID_PARAM,
               status=None, param_filled=True):
    return {"method": method, "scenario": scenario, "class": "validation",
            "verb": verb, "path_template": path_template,
            "variants": variants,
            "expected_status": status or [400, 422],
            "expected_message_substring": msg,
            "expected_message_param_filled": param_filled}

def method_verb(method):
    if method.startswith("Create"): return "POST"
    if method.startswith("Get"):    return "GET"
    if method.startswith("List"):   return "GET"
    if method.startswith("Delete"): return "DELETE"
    if method.startswith("Update"): return "PUT"
    return "POST"


def write(method_snake, method_camel, rows):
    out_path = HERE / f"{method_snake}.json"
    # ID prefix from CamelCase initials.
    initials = "".join(c for c in method_camel if c.isupper())
    for i, r in enumerate(rows, 1):
        r["id"] = f"{initials}-{i:03d}"
        r["source"] = f"Confluence > {method_camel}"
    out_path.write_text(json.dumps(rows, indent=2), encoding="utf-8")
    print(f"  wrote {out_path.name}: {len(rows)} rows")


# ------------------------------------------------------------ Get KB

write("get_knowledge_base", "GetKnowledgeBase", [
    validation("GetKnowledgeBase",
               "idlOcid / catalogId / schemaId / displayName missing or blank",
               "GET", "/knowledgeBases/{kb_key}",
               [{"name": "blank kb_key", "path_params": {"kb_key": " "}}]),
    infra("GetKnowledgeBase",
          "KB feature configuration cannot be read from the lake property bag",
          SUB_FEATURE_CFG),
    infra("GetKnowledgeBase",
          "KB feature is disabled (DISABLING allowed)",
          SUB_FEATURE_OFF),
    fixture_not_found("GetKnowledgeBase",
                      "Knowledge Base not found by validateKnowledgeBaseExist",
                      "/knowledgeBases/{kb_key}",
                      "Not found. The requested Knowledge Base"),
    dbinject("GetKnowledgeBase",
             "DB connection failed while getting the Knowledge Base",
             SUB_DB_FAIL),
    dbinject("GetKnowledgeBase",
             "Embedding model does not exist (ORA-40284)",
             SUB_EMBEDDING),
    validation("GetKnowledgeBase",
               "Invalid request signal reaches get classifier",
               "GET", "/knowledgeBases/{kb_key}",
               [{"name": "wildcard chars", "path_params": {"kb_key": "***"}}],
               msg=SUB_INVALID_GENERIC, param_filled=False),
    race("GetKnowledgeBase",
         "Get operation times out",
         "Operation timed out. Getting the Knowledge Base did not complete in time."),
    infra("GetKnowledgeBase",
          "Other dependency failure while getting the Knowledge Base",
          "Service unavailable. A dependent service failed while getting"),
])

# ------------------------------------------------------------ Update KB

write("update_knowledge_base", "UpdateKnowledgeBase", [
    validation("UpdateKnowledgeBase",
               "knowledgebase / idlOcid / catalog / schema missing or blank",
               "PUT", "/knowledgeBases/{kb_key}",
               [{"name": "blank kb_key", "path_params": {"kb_key": " "},
                 "body": {"action": "UPDATE_METADATA", "metadataUpdate": {"description": "x"}}}]),
    validation("UpdateKnowledgeBase",
               "Update request body is null",
               "PUT", "/knowledgeBases/{kb_key}",
               [{"name": "null body", "path_params": {"kb_key": "kb1"}, "body": None}],
               msg="Input - updateKnowledgeBaseDetails is null"),
    validation("UpdateKnowledgeBase",
               "Update action missing",
               "PUT", "/knowledgeBases/{kb_key}",
               [{"name": "no action", "path_params": {"kb_key": "kb1"}, "body": {}}],
               msg="no action (KnowledgeBaseUpdateOperationType) specified"),
    validation("UpdateKnowledgeBase",
               "Metadata update details missing",
               "PUT", "/knowledgeBases/{kb_key}",
               [{"name": "no metadataUpdate", "path_params": {"kb_key": "kb1"},
                 "body": {"action": "UPDATE_METADATA"}}],
               msg="Input for KB metadata update"),
    validation("UpdateKnowledgeBase",
               "Metadata update both name and description empty",
               "PUT", "/knowledgeBases/{kb_key}",
               [{"name": "both empty", "path_params": {"kb_key": "kb1"},
                 "body": {"action": "UPDATE_METADATA", "metadataUpdate": {"description": "", "name": ""}}}],
               msg="both name and description are empty"),
    validation("UpdateKnowledgeBase",
               "Source update details missing",
               "PUT", "/knowledgeBases/{kb_key}",
               [{"name": "no source body", "path_params": {"kb_key": "kb1"},
                 "body": {"action": "UPDATE_SOURCES"}}],
               msg="Input for KB source update"),
    validation("UpdateKnowledgeBase",
               "Source update list empty",
               "PUT", "/knowledgeBases/{kb_key}",
               [{"name": "empty sources list", "path_params": {"kb_key": "kb1"},
                 "body": {"action": "UPDATE_SOURCES", "sourceUpdate": {"sources": []}}}],
               msg="empty payload"),
    validation("UpdateKnowledgeBase",
               "Add-source payload null",
               "PUT", "/knowledgeBases/{kb_key}",
               [{"name": "null add payload", "path_params": {"kb_key": "kb1"},
                 "body": {"action": "UPDATE_SOURCES", "sourceUpdate":
                          {"sources": [{"action": "ADD", "addSource": None}]}}}],
               msg="Null payload for Add source"),
    validation("UpdateKnowledgeBase",
               "Add-source missing name/type/location",
               "PUT", "/knowledgeBases/{kb_key}",
               [{"name": "incomplete add", "path_params": {"kb_key": "kb1"},
                 "body": {"action": "UPDATE_SOURCES", "sourceUpdate":
                          {"sources": [{"action": "ADD", "addSource": {"name": "x"}}]}}}],
               msg="Add source body not well formed"),
    validation("UpdateKnowledgeBase",
               "Add-source uses unsupported Table type",
               "PUT", "/knowledgeBases/{kb_key}",
               [{"name": "table type", "path_params": {"kb_key": "kb1"},
                 "body": {"action": "UPDATE_SOURCES", "sourceUpdate":
                          {"sources": [{"action": "ADD",
                                       "addSource": {"name": "x", "type": "Table",
                                                     "location": "..."}}]}}}],
               msg="Table is not supported yet"),
    validation("UpdateKnowledgeBase",
               "Delete-source payload null",
               "PUT", "/knowledgeBases/{kb_key}",
               [{"name": "null delete payload", "path_params": {"kb_key": "kb1"},
                 "body": {"action": "UPDATE_SOURCES", "sourceUpdate":
                          {"sources": [{"action": "DELETE", "deleteSource": None}]}}}],
               msg="Null payload for Delete source"),
    validation("UpdateKnowledgeBase",
               "Delete-source missing name/type",
               "PUT", "/knowledgeBases/{kb_key}",
               [{"name": "incomplete delete", "path_params": {"kb_key": "kb1"},
                 "body": {"action": "UPDATE_SOURCES", "sourceUpdate":
                          {"sources": [{"action": "DELETE", "deleteSource": {}}]}}}],
               msg="Delete source body not well formed"),
    validation("UpdateKnowledgeBase",
               "Add-index missing indexDetails",
               "PUT", "/knowledgeBases/{kb_key}",
               [{"name": "no indexDetails", "path_params": {"kb_key": "kb1"},
                 "body": {"action": "ADD_INDEX"}}],
               msg="Index details are required"),
    validation("UpdateKnowledgeBase",
               "Add-index missing index type",
               "PUT", "/knowledgeBases/{kb_key}",
               [{"name": "no index type", "path_params": {"kb_key": "kb1"},
                 "body": {"action": "ADD_INDEX", "indexDetails": {}}}],
               msg="Index type is required"),
    {"method": "UpdateKnowledgeBase",
     "scenario": "Add-source name already exists",
     "class": "fixture",
     "fixture_required": "create_kb_with_source_then_add_same",
     "expected_status": [400, 409],
     "expected_message_substring": "already exists in this Knowledge Base."},
    {"method": "UpdateKnowledgeBase",
     "scenario": "Add-source location already tracked",
     "class": "fixture",
     "fixture_required": "create_kb_with_location_then_add_same",
     "expected_status": [400, 409],
     "expected_message_substring": "is already tracked by this Knowledge Base."},
    {"method": "UpdateKnowledgeBase",
     "scenario": "Add-source location overlaps existing source",
     "class": "fixture",
     "fixture_required": "create_kb_with_location_then_add_overlap",
     "expected_status": [400],
     "expected_message_substring": "sources cannot have overlapping locations."},
    infra("UpdateKnowledgeBase",
          "Add-index when KB already has index metadata",
          "Service unavailable. A dependent service failed while updating"),
    infra("UpdateKnowledgeBase",
          "Add-index unsupported index type after validation",
          "Service unavailable. A dependent service failed while updating"),
    infra("UpdateKnowledgeBase",
          "Drop-index when KB has no index type",
          "Service unavailable. A dependent service failed while updating"),
    fixture_not_found("UpdateKnowledgeBase",
                      "Drop-index finds type but stored index name is missing",
                      "/knowledgeBases/{kb_key}",
                      SUB_NOT_FOUND_KB),
    noop("UpdateKnowledgeBase",
         "Delete-source target name/type does not match any current source row",
         "Delete SQL result not validated; continues without reporting no match."),
    noop("UpdateKnowledgeBase",
         "Drop-index DDL fails but metadata cleanup succeeds",
         "DDL failure logged; metadata still cleared."),
    infra("UpdateKnowledgeBase",
          "KB feature configuration cannot be read",
          SUB_FEATURE_CFG),
    infra("UpdateKnowledgeBase",
          "KB feature is disabled",
          SUB_FEATURE_OFF),
    infra("UpdateKnowledgeBase",
          "Normal update path cannot load the KB row",
          "Service unavailable. A dependent service failed while updating"),
    fixture_not_found("UpdateKnowledgeBase",
                      "Downstream update exception contains 'not found' / 'does not exist'",
                      "/knowledgeBases/{kb_key}",
                      SUB_NOT_FOUND_KB),
    infra("UpdateKnowledgeBase",
          "Default cluster is not active or is unavailable",
          SUB_CLUSTER_DOWN),
    race("UpdateKnowledgeBase",
         "Job definition/checksum changed before inline job run could start",
         "Conflict. The Knowledge Base job definition changed"),
    dbinject("UpdateKnowledgeBase",
             "DB connection timed out during update (ORA-12170)",
             SUB_DB_TIMEOUT),
    dbinject("UpdateKnowledgeBase",
             "DB connection failed during update (ORA-12514 / TNS)",
             SUB_DB_FAIL),
    dbinject("UpdateKnowledgeBase",
             "DB resources insufficient during update (ORA-65114)",
             SUB_DB_RES),
    dbinject("UpdateKnowledgeBase",
             "Embedding model does not exist (ORA-40284)",
             SUB_EMBEDDING),
    dbinject("UpdateKnowledgeBase",
             "Other database-originated update error (ORA / SQLException)",
             SUB_DB_OP),
    {"method": "UpdateKnowledgeBase",
     "scenario": "Inline job-run fails with standardized message already persisted",
     "class": "noop",
     "notes": "Async preserves rendered job-run message; not testable from update API.",
     "expected_status": [200, 202]},
    infra("UpdateKnowledgeBase",
          "Inline job-run Failed but fail-fast had no runData",
          "Service unavailable. A dependent service failed while updating"),
    validation("UpdateKnowledgeBase",
               "Invalid request signal reaches update classifier",
               "PUT", "/knowledgeBases/{kb_key}",
               [{"name": "malformed", "path_params": {"kb_key": "kb1"},
                 "body": {"action": "BOGUS_ACTION"}}],
               msg=SUB_INVALID_GENERIC, param_filled=False),
    race("UpdateKnowledgeBase",
         "Update operation times out",
         "Operation timed out. Knowledge Base update did not complete in time."),
    infra("UpdateKnowledgeBase",
          "Other dependency failure while updating",
          "Service unavailable. A dependent service failed while updating"),
    noop("UpdateKnowledgeBase",
         "Success callback fails to publish metadata/source lineage events"),
])

# ------------------------------------------------------------ Delete KB

write("delete_knowledge_base", "DeleteKnowledgeBase", [
    validation("DeleteKnowledgeBase",
               "idlOcid / catalogId / schemaId / kb missing or blank",
               "DELETE", "/knowledgeBases/{kb_key}",
               [{"name": "blank kb_key", "path_params": {"kb_key": " "}}]),
    infra("DeleteKnowledgeBase", "KB feature config unreadable", SUB_FEATURE_CFG),
    infra("DeleteKnowledgeBase", "KB feature disabled", SUB_FEATURE_OFF),
    noop("DeleteKnowledgeBase",
         "Normal delete lookup does not find the KB",
         "KbService.deleteKnowledgeBase returns without creating async work."),
    fixture_not_found("DeleteKnowledgeBase",
                      "Downstream delete exception contains 'not found'",
                      "/knowledgeBases/{kb_key}",
                      SUB_NOT_FOUND_KB),
    infra("DeleteKnowledgeBase", "Default cluster unavailable", SUB_CLUSTER_DOWN),
    noop("DeleteKnowledgeBase",
         "Delete-table DDL reports ORA-00942 (table not found)",
         "Intentionally ignored."),
    noop("DeleteKnowledgeBase",
         "Failure deleting child KB jobs",
         "Logged and ignored."),
    noop("DeleteKnowledgeBase",
         "Metadata delete affects zero rows",
         "Final delete count not validated."),
    dbinject("DeleteKnowledgeBase", "Embedding model does not exist", SUB_EMBEDDING),
    validation("DeleteKnowledgeBase",
               "Invalid request signal reaches delete classifier",
               "DELETE", "/knowledgeBases/{kb_key}",
               [{"name": "wildcards", "path_params": {"kb_key": "***"}}],
               msg=SUB_INVALID_GENERIC, param_filled=False),
    race("DeleteKnowledgeBase",
         "Delete operation times out",
         "Operation timed out. Knowledge Base deletion did not complete in time."),
    infra("DeleteKnowledgeBase",
          "Other dependency failure while deleting",
          "Service unavailable. A dependent service failed while deleting"),
    noop("DeleteKnowledgeBase",
         "Success callback fails to publish the delete event"),
])

# ------------------------------------------------------------ Create KB Job

write("create_kb_job", "CreateKnowledgeBaseJob", [
    {"method": "CreateKnowledgeBaseJob",
     "scenario": "Request body is null",
     "class": "validation",
     "verb": "POST", "path_template": "/knowledgeBases/{kb_key}/jobs",
     "variants": [{"name": "null body", "path_params": {"kb_key": "kb1"}, "body": None}],
     "expected_status": [400, 415, 500],
     "expected_message_substring": "",
     "notes": "Body dereferenced before KB catalog; framework responds."},
    validation("CreateKnowledgeBaseJob",
               "idlOcid / catalogId / schemaId / displayName / knowledgeBaseId missing",
               "POST", "/knowledgeBases/{kb_key}/jobs",
               [{"name": "blank fields", "path_params": {"kb_key": "kb1"},
                 "body": {"idlOcid": "", "displayName": ""}}]),
    infra("CreateKnowledgeBaseJob", "KB feature config unreadable", SUB_FEATURE_CFG),
    infra("CreateKnowledgeBaseJob", "KB feature disabled", SUB_FEATURE_OFF),
    fixture_not_found("CreateKnowledgeBaseJob",
                      "Parent KB not found",
                      "/knowledgeBases/{kb_key}/jobs",
                      "Not found. The requested Knowledge Base"),
    {"method": "CreateKnowledgeBaseJob",
     "scenario": "KB job already exists",
     "class": "fixture",
     "fixture_required": "create_job_then_recreate",
     "expected_status": [409],
     "expected_message_substring": "Knowledge Base job already exists."},
    dbinject("CreateKnowledgeBaseJob", "Embedding model does not exist", SUB_EMBEDDING),
    validation("CreateKnowledgeBaseJob",
               "Invalid request signal reaches job-create classifier",
               "POST", "/knowledgeBases/{kb_key}/jobs",
               [{"name": "malformed", "path_params": {"kb_key": "kb1"}, "body": {"x": 1}}],
               msg=SUB_INVALID_GENERIC, param_filled=False),
    race("CreateKnowledgeBaseJob",
         "Create job operation times out",
         "Operation timed out. Knowledge Base job creation did not complete in time."),
    infra("CreateKnowledgeBaseJob",
          "Workflow service / checksum / metadata insert fails",
          "Service unavailable. A dependent service failed while creating the Knowledge Base job."),
    noop("CreateKnowledgeBaseJob",
         "Success callback fails to publish the create-job event"),
])

# ------------------------------------------------------------ List KB Jobs

write("list_kb_jobs", "ListKnowledgeBaseJobs", [
    validation("ListKnowledgeBaseJobs",
               "idlOcid / catalogId / schemaId / knowledgeBaseId missing",
               "GET", "/knowledgeBases/{kb_key}/jobs",
               [{"name": "blank kb", "path_params": {"kb_key": " "}}]),
    validation("ListKnowledgeBaseJobs",
               "limit outside 1..1000",
               "GET", "/knowledgeBases/{kb_key}/jobs",
               [{"name": "limit=0",     "path_params": {"kb_key": "kb1"}, "query": {"limit": "0"}},
                {"name": "limit=10000", "path_params": {"kb_key": "kb1"}, "query": {"limit": "10000"}}],
               msg="Limit must be between 1 and 1000", param_filled=False),
    validation("ListKnowledgeBaseJobs",
               "page token blank",
               "GET", "/knowledgeBases/{kb_key}/jobs",
               [{"name": "blank page", "path_params": {"kb_key": "kb1"}, "query": {"page": ""}}],
               msg="Page token cannot be empty", param_filled=False),
    noop("ListKnowledgeBaseJobs",
         "Nonblank page token malformed",
         "Logs parse error, ignores pagination."),
    infra("ListKnowledgeBaseJobs", "KB feature config unreadable", SUB_FEATURE_CFG),
    infra("ListKnowledgeBaseJobs", "KB feature disabled", SUB_FEATURE_OFF),
    noop("ListKnowledgeBaseJobs",
         "Parent KB does not exist in normal list query",
         "Subquery returns no jobs; empty collection."),
    fixture_not_found("ListKnowledgeBaseJobs",
                      "Downstream list-jobs exception contains 'not found'",
                      "/knowledgeBases/{kb_key}/jobs",
                      SUB_NOT_FOUND_KB),
    dbinject("ListKnowledgeBaseJobs", "Embedding model does not exist", SUB_EMBEDDING),
    validation("ListKnowledgeBaseJobs",
               "Invalid request signal reaches job-list classifier",
               "GET", "/knowledgeBases/{kb_key}/jobs",
               [{"name": "wildcards", "path_params": {"kb_key": "***"}}],
               msg=SUB_INVALID_GENERIC, param_filled=False),
    race("ListKnowledgeBaseJobs",
         "List jobs operation times out",
         "Operation timed out. Listing Knowledge Base jobs did not complete in time."),
    infra("ListKnowledgeBaseJobs",
          "Other dependency failure while listing jobs",
          "Service unavailable. A dependent service failed while listing"),
])

# ------------------------------------------------------------ Get KB Job

write("get_kb_job", "GetKnowledgeBaseJob", [
    validation("GetKnowledgeBaseJob",
               "idlOcid / catalogId / schemaId / kbName / jobName missing",
               "GET", "/knowledgeBases/{kb_key}/jobs/{job_key}",
               [{"name": "blank job_key",
                 "path_params": {"kb_key": "kb1", "job_key": " "}}]),
    infra("GetKnowledgeBaseJob", "KB feature config unreadable", SUB_FEATURE_CFG),
    infra("GetKnowledgeBaseJob", "KB feature disabled", SUB_FEATURE_OFF),
    fixture_not_found("GetKnowledgeBaseJob",
                      "Parent KB not found",
                      "/knowledgeBases/{kb_key}/jobs/{job_key}",
                      "Not found. The requested Knowledge Base job"),
    fixture_not_found("GetKnowledgeBaseJob",
                      "KB job not found",
                      "/knowledgeBases/{kb_key}/jobs/{job_key}",
                      "Not found. The requested Knowledge Base job"),
    dbinject("GetKnowledgeBaseJob", "Embedding model does not exist", SUB_EMBEDDING),
    validation("GetKnowledgeBaseJob",
               "Invalid request signal reaches job-get classifier",
               "GET", "/knowledgeBases/{kb_key}/jobs/{job_key}",
               [{"name": "wildcards", "path_params": {"kb_key": "***", "job_key": "***"}}],
               msg=SUB_INVALID_GENERIC, param_filled=False),
    race("GetKnowledgeBaseJob",
         "Get job operation times out",
         "Operation timed out. Getting the Knowledge Base job did not complete in time."),
    infra("GetKnowledgeBaseJob",
          "Other dependency failure while getting the job",
          "Service unavailable. A dependent service failed while getting"),
])

# ------------------------------------------------------------ Delete KB Job

write("delete_kb_job", "DeleteKnowledgeBaseJob", [
    {"method": "DeleteKnowledgeBaseJob",
     "scenario": "idlOcid missing or blank",
     "class": "noop",
     "notes": "No guaranteed required-param message; feature flag check comes first.",
     "expected_status": [400, 404]},
    validation("DeleteKnowledgeBaseJob",
               "catalogId / schemaId / kb / job missing after feature validation",
               "DELETE", "/knowledgeBases/{kb_key}/jobs/{job_key}",
               [{"name": "blank job_key",
                 "path_params": {"kb_key": "kb1", "job_key": " "}}]),
    infra("DeleteKnowledgeBaseJob", "KB feature config unreadable", SUB_FEATURE_CFG),
    infra("DeleteKnowledgeBaseJob", "KB feature disabled", SUB_FEATURE_OFF),
    fixture_not_found("DeleteKnowledgeBaseJob",
                      "Parent KB not found",
                      "/knowledgeBases/{kb_key}/jobs/{job_key}",
                      "Not found. The requested Knowledge Base job"),
    fixture_not_found("DeleteKnowledgeBaseJob",
                      "KB job not found",
                      "/knowledgeBases/{kb_key}/jobs/{job_key}",
                      "Not found. The requested Knowledge Base job"),
    dbinject("DeleteKnowledgeBaseJob", "Embedding model does not exist", SUB_EMBEDDING),
    validation("DeleteKnowledgeBaseJob",
               "Invalid request signal reaches job-delete classifier",
               "DELETE", "/knowledgeBases/{kb_key}/jobs/{job_key}",
               [{"name": "wildcards", "path_params": {"kb_key": "***", "job_key": "***"}}],
               msg=SUB_INVALID_GENERIC, param_filled=False),
    race("DeleteKnowledgeBaseJob",
         "Delete job operation times out",
         "Operation timed out. Knowledge Base job deletion did not complete in time."),
    infra("DeleteKnowledgeBaseJob",
          "Workflow service delete / metadata count / dep failure",
          "Service unavailable. A dependent service failed while deleting the Knowledge Base job."),
    noop("DeleteKnowledgeBaseJob",
         "Success callback fails to publish delete-job event"),
])

# ------------------------------------------------------------ Create KB Job Run

write("create_kb_job_run", "CreateKnowledgeBaseJobRun", [
    {"method": "CreateKnowledgeBaseJobRun",
     "scenario": "Request body is null",
     "class": "validation",
     "verb": "POST", "path_template": "/knowledgeBases/{kb_key}/jobs/{job_key}/runs",
     "variants": [{"name": "null body",
                   "path_params": {"kb_key": "kb1", "job_key": "j1"},
                   "body": None}],
     "expected_status": [400, 415, 500],
     "expected_message_substring": "",
     "notes": "Framework handles null body."},
    validation("CreateKnowledgeBaseJobRun",
               "idlOcid / knowledgeBaseId / knowledgeBaseJobId / catalog / schema missing",
               "POST", "/knowledgeBases/{kb_key}/jobs/{job_key}/runs",
               [{"name": "blank kb", "path_params": {"kb_key": " ", "job_key": "j1"},
                 "body": {"x": 1}}]),
    infra("CreateKnowledgeBaseJobRun", "KB feature config unreadable", SUB_FEATURE_CFG),
    infra("CreateKnowledgeBaseJobRun", "KB feature disabled", SUB_FEATURE_OFF),
    fixture_not_found("CreateKnowledgeBaseJobRun",
                      "Parent KB not found",
                      "/knowledgeBases/{kb_key}/jobs/{job_key}/runs",
                      "Not found. The requested Knowledge Base job run"),
    fixture_not_found("CreateKnowledgeBaseJobRun",
                      "Parent KB job not found",
                      "/knowledgeBases/{kb_key}/jobs/{job_key}/runs",
                      "Not found. The requested Knowledge Base job run"),
    race("CreateKnowledgeBaseJobRun",
         "Job definition checksum changed before run created",
         "Conflict. The Knowledge Base job definition changed"),
    dbinject("CreateKnowledgeBaseJobRun", "Embedding model does not exist", SUB_EMBEDDING),
    validation("CreateKnowledgeBaseJobRun",
               "Invalid request signal reaches job-run-create classifier",
               "POST", "/knowledgeBases/{kb_key}/jobs/{job_key}/runs",
               [{"name": "wildcards", "path_params": {"kb_key": "***", "job_key": "***"},
                 "body": {"x": 1}}],
               msg=SUB_INVALID_GENERIC, param_filled=False),
    race("CreateKnowledgeBaseJobRun",
         "Create job run operation times out",
         "Operation timed out. Knowledge Base job run did not start in time."),
    infra("CreateKnowledgeBaseJobRun",
          "Job-run metadata insert / workflow / dep failure",
          "Service unavailable. A dependent service failed while starting the Knowledge Base job run."),
])

# ------------------------------------------------------------ List KB Job Runs

write("list_kb_job_runs", "ListKnowledgeBaseJobRun", [
    validation("ListKnowledgeBaseJobRun",
               "idlOcid / catalogId / schemaId missing",
               "GET", "/knowledgeBases/{kb_key}/jobs/{job_key}/runs",
               [{"name": "blank kb",
                 "path_params": {"kb_key": " ", "job_key": "j1"}}]),
    {"method": "ListKnowledgeBaseJobRun",
     "scenario": "knowledgeBaseId / knowledgeBaseJobId missing or blank",
     "class": "noop",
     "notes": "No direct required-param message; validates parent existence instead.",
     "expected_status": [200, 404]},
    noop("ListKnowledgeBaseJobRun",
         "limit zero, negative, or over 1000",
         "Pagination not validated."),
    noop("ListKnowledgeBaseJobRun",
         "page token blank",
         "Token ignored."),
    noop("ListKnowledgeBaseJobRun",
         "Nonblank page token malformed",
         "Parse error logged; pagination ignored."),
    infra("ListKnowledgeBaseJobRun", "KB feature config unreadable", SUB_FEATURE_CFG),
    infra("ListKnowledgeBaseJobRun", "KB feature disabled", SUB_FEATURE_OFF),
    fixture_not_found("ListKnowledgeBaseJobRun",
                      "Parent KB not found",
                      "/knowledgeBases/{kb_key}/jobs/{job_key}/runs",
                      SUB_NOT_FOUND_JOB),
    fixture_not_found("ListKnowledgeBaseJobRun",
                      "Parent KB job not found",
                      "/knowledgeBases/{kb_key}/jobs/{job_key}/runs",
                      SUB_NOT_FOUND_JOB),
    noop("ListKnowledgeBaseJobRun",
         "Accepted job-run workflow status check fails",
         "Existing job run returned."),
    noop("ListKnowledgeBaseJobRun",
         "Accepted workflow failed; fail-fast had no runData",
         "Pre-update row shown; no standardized lifecycle detail."),
    dbinject("ListKnowledgeBaseJobRun", "Embedding model does not exist", SUB_EMBEDDING),
    validation("ListKnowledgeBaseJobRun",
               "Invalid request signal reaches job-run-list classifier",
               "GET", "/knowledgeBases/{kb_key}/jobs/{job_key}/runs",
               [{"name": "wildcards", "path_params": {"kb_key": "***", "job_key": "***"}}],
               msg=SUB_INVALID_GENERIC, param_filled=False),
    race("ListKnowledgeBaseJobRun",
         "List job runs operation times out",
         "Operation timed out. Listing Knowledge Base job runs did not complete in time."),
    infra("ListKnowledgeBaseJobRun",
          "Other dependency failure while listing job runs",
          "Service unavailable. A dependent service failed while listing Knowledge Base job runs."),
])

# ------------------------------------------------------------ Get KB Job Run

write("get_kb_job_run", "GetKnowledgeBaseJobRun", [
    {"method": "GetKnowledgeBaseJobRun",
     "scenario": "idlOcid / catalogId / schemaId / KB / job / run missing",
     "class": "noop",
     "notes": "No direct required-param check; flows into feature lookup + parent lookup.",
     "expected_status": [400, 404]},
    infra("GetKnowledgeBaseJobRun", "KB feature config unreadable", SUB_FEATURE_CFG),
    infra("GetKnowledgeBaseJobRun", "KB feature disabled", SUB_FEATURE_OFF),
    fixture_not_found("GetKnowledgeBaseJobRun",
                      "Parent KB not found",
                      "/knowledgeBases/{kb_key}/jobs/{job_key}/runs/{run_key}",
                      SUB_NOT_FOUND_RUN),
    fixture_not_found("GetKnowledgeBaseJobRun",
                      "Parent KB job not found",
                      "/knowledgeBases/{kb_key}/jobs/{job_key}/runs/{run_key}",
                      SUB_NOT_FOUND_RUN),
    fixture_not_found("GetKnowledgeBaseJobRun",
                      "KB job run not found",
                      "/knowledgeBases/{kb_key}/jobs/{job_key}/runs/{run_key}",
                      SUB_NOT_FOUND_RUN),
    noop("GetKnowledgeBaseJobRun",
         "Accepted job-run workflow status check fails",
         "Catches the exception, returns existing run."),
    noop("GetKnowledgeBaseJobRun",
         "Accepted workflow failed but fail-fast had no runData",
         "Response may show Failed with no standardized detail."),
    dbinject("GetKnowledgeBaseJobRun", "Embedding model does not exist", SUB_EMBEDDING),
    validation("GetKnowledgeBaseJobRun",
               "Invalid request signal reaches job-run-get classifier",
               "GET", "/knowledgeBases/{kb_key}/jobs/{job_key}/runs/{run_key}",
               [{"name": "wildcards", "path_params": {"kb_key": "***", "job_key": "***", "run_key": "***"}}],
               msg=SUB_INVALID_GENERIC, param_filled=False),
    race("GetKnowledgeBaseJobRun",
         "Get job run operation times out",
         "Operation timed out. Getting the Knowledge Base job run did not complete in time."),
    infra("GetKnowledgeBaseJobRun",
          "Other dependency failure",
          "Service unavailable. A dependent service failed while getting the Knowledge Base job run."),
])

# ------------------------------------------------------------ Update KB Job Run

write("update_kb_job_run", "UpdateKnowledgeBaseJobRun", [
    {"method": "UpdateKnowledgeBaseJobRun",
     "scenario": "idlOcid / catalog / schema / KB / job / run missing",
     "class": "noop",
     "notes": "No direct required-param check.",
     "expected_status": [400, 404]},
    infra("UpdateKnowledgeBaseJobRun", "KB feature config unreadable", SUB_FEATURE_CFG),
    infra("UpdateKnowledgeBaseJobRun", "KB feature disabled", SUB_FEATURE_OFF),
    validation("UpdateKnowledgeBaseJobRun",
               "Update body null or both runData and lifecycleState missing",
               "PUT", "/knowledgeBases/{kb_key}/jobs/{job_key}/runs/{run_key}",
               [{"name": "empty body",
                 "path_params": {"kb_key": "kb1", "job_key": "j1", "run_key": "r1"},
                 "body": {}}],
               msg="Update details are missing.", param_filled=False),
    fixture_not_found("UpdateKnowledgeBaseJobRun",
                      "Parent KB not found",
                      "/knowledgeBases/{kb_key}/jobs/{job_key}/runs/{run_key}",
                      SUB_NOT_FOUND_RUN),
    fixture_not_found("UpdateKnowledgeBaseJobRun",
                      "Parent KB job not found",
                      "/knowledgeBases/{kb_key}/jobs/{job_key}/runs/{run_key}",
                      SUB_NOT_FOUND_RUN),
    fixture_not_found("UpdateKnowledgeBaseJobRun",
                      "KB job run not found",
                      "/knowledgeBases/{kb_key}/jobs/{job_key}/runs/{run_key}",
                      SUB_NOT_FOUND_RUN),
    dbinject("UpdateKnowledgeBaseJobRun",
             "lifecycleState=Failed + ORA-40284 + runData",
             SUB_EMBEDDING),
    dbinject("UpdateKnowledgeBaseJobRun",
             "lifecycleState=Failed + ORA-12170 + runData",
             SUB_DB_TIMEOUT),
    dbinject("UpdateKnowledgeBaseJobRun",
             "lifecycleState=Failed + ORA-12514 + runData",
             SUB_DB_FAIL),
    dbinject("UpdateKnowledgeBaseJobRun",
             "lifecycleState=Failed + ORA-65114 + runData",
             SUB_DB_RES),
    dbinject("UpdateKnowledgeBaseJobRun",
             "lifecycleState=Failed + other ORA / SQLException + runData",
             SUB_DB_OP),
    dbinject("UpdateKnowledgeBaseJobRun",
             "lifecycleState=Failed + generic invalid request text + runData",
             SUB_INVALID_GENERIC),
    dbinject("UpdateKnowledgeBaseJobRun",
             "lifecycleState=Failed + timeout text + runData",
             "Operation timed out. Updating the Knowledge Base job run did not complete in time."),
    dbinject("UpdateKnowledgeBaseJobRun",
             "lifecycleState=Failed + unclassified + runData",
             "Service unavailable. A dependent service failed while updating the Knowledge Base job run."),
    noop("UpdateKnowledgeBaseJobRun",
         "Failed with lifecycleStateDetails but no runData",
         "No standardized lifecycle detail persisted."),
    {"method": "UpdateKnowledgeBaseJobRun",
     "scenario": "Updating current processed item count fails",
     "class": "infra",
     "skip_reason": "Maps to one of the DB/dep messages above.",
     "expected_message_substring": SUB_DB_OP},
    noop("UpdateKnowledgeBaseJobRun",
         "Completion event emission fails after Succeeded/Failed"),
    validation("UpdateKnowledgeBaseJobRun",
               "Invalid request signal reaches job-run-update classifier",
               "PUT", "/knowledgeBases/{kb_key}/jobs/{job_key}/runs/{run_key}",
               [{"name": "wildcards",
                 "path_params": {"kb_key": "***", "job_key": "***", "run_key": "***"},
                 "body": {"x": 1}}],
               msg=SUB_INVALID_GENERIC, param_filled=False),
    race("UpdateKnowledgeBaseJobRun",
         "Update job run operation times out",
         "Operation timed out. Updating the Knowledge Base job run did not complete in time."),
    infra("UpdateKnowledgeBaseJobRun",
          "Other dependency failure",
          "Service unavailable. A dependent service failed while updating the Knowledge Base job run."),
])

# ------------------------------------------------------------ Update KB Owner

write("update_kb_owner", "UpdateKnowledgeBaseOwner", [
    {"method": "UpdateKnowledgeBaseOwner",
     "scenario": "idlOcid missing or blank",
     "class": "noop",
     "notes": "No guaranteed required-param message; feature flag check first.",
     "expected_status": [400, 404]},
    {"method": "UpdateKnowledgeBaseOwner",
     "scenario": "Request body is null",
     "class": "validation",
     "verb": "POST", "path_template": "/knowledgeBases/{kb_key}/actions/updateOwner",
     "variants": [{"name": "null body", "path_params": {"kb_key": "kb1"}, "body": None}],
     "expected_status": [400, 415, 500],
     "expected_message_substring": "",
     "notes": "Framework handles null body."},
    validation("UpdateKnowledgeBaseOwner",
               "catalogKey / schemaKey / knowledgeBaseName missing after feature validation",
               "POST", "/knowledgeBases/{kb_key}/actions/updateOwner",
               [{"name": "blank fields", "path_params": {"kb_key": "kb1"},
                 "body": {"catalogKey": "", "schemaKey": ""}}]),
    infra("UpdateKnowledgeBaseOwner", "KB feature config unreadable", SUB_FEATURE_CFG),
    infra("UpdateKnowledgeBaseOwner", "KB feature disabled", SUB_FEATURE_OFF),
    infra("UpdateKnowledgeBaseOwner",
          "Normal owner update path cannot load KB row",
          "Service unavailable. A dependent service failed while updating the Knowledge Base owner."),
    fixture_not_found("UpdateKnowledgeBaseOwner",
                      "Downstream owner-update exception contains 'not found'",
                      "/knowledgeBases/{kb_key}/actions/updateOwner",
                      SUB_NOT_FOUND_KB),
    noop("UpdateKnowledgeBaseOwner",
         "Ownership already revoked or flag is null",
         "Treated as no-op."),
    dbinject("UpdateKnowledgeBaseOwner", "Embedding model does not exist", SUB_EMBEDDING),
    validation("UpdateKnowledgeBaseOwner",
               "Invalid request signal reaches owner-update classifier",
               "POST", "/knowledgeBases/{kb_key}/actions/updateOwner",
               [{"name": "wildcards", "path_params": {"kb_key": "***"}, "body": {"x": 1}}],
               msg=SUB_INVALID_GENERIC, param_filled=False),
    race("UpdateKnowledgeBaseOwner",
         "Owner update operation times out",
         "Operation timed out. Updating the Knowledge Base owner did not complete in time."),
    infra("UpdateKnowledgeBaseOwner",
          "Other dependency failure",
          "Service unavailable. A dependent service failed while updating the Knowledge Base owner."),
])

# ------------------------------------------------------------ Get Vector Store Credentials

write("get_vector_store_credentials", "GetVectorStoreCredentials", [
    validation("GetVectorStoreCredentials",
               "idlOcid / knowledgeBaseId / catalogName / schemaName missing",
               "GET", "/knowledgeBases/{kb_key}/vectorStoreCredentials",
               [{"name": "blank kb_key", "path_params": {"kb_key": " "}}]),
    infra("GetVectorStoreCredentials", "KB feature config unreadable", SUB_FEATURE_CFG),
    infra("GetVectorStoreCredentials", "KB feature disabled", SUB_FEATURE_OFF),
    fixture_not_found("GetVectorStoreCredentials",
                      "KB not found by validateKnowledgeBaseExist",
                      "/knowledgeBases/{kb_key}/vectorStoreCredentials",
                      "Not found. The requested Knowledge Base"),
    infra("GetVectorStoreCredentials",
          "Vector store configuration missing or incomplete",
          "Service unavailable. The Knowledge Base database configuration is missing or incomplete."),
    infra("GetVectorStoreCredentials",
          "Dependent service fails retrieving catalog connection data",
          "Service unavailable. A dependent service failed while retrieving database connection details."),
    infra("GetVectorStoreCredentials",
          "Dependent service fails retrieving database credentials",
          "Service unavailable. A dependent service failed while retrieving database credentials."),
    infra("GetVectorStoreCredentials",
          "Credential response missing username/password or malformed",
          "Service unavailable. Database credentials are missing or invalid."),
    infra("GetVectorStoreCredentials",
          "Wallet content missing/empty/base64-undecodable/un-unzippable",
          "Invalid database wallet. The database wallet content could not be decoded."),
    infra("GetVectorStoreCredentials",
          "Wallet missing required files (cwallet.sso / tnsnames.ora)",
          "Invalid database wallet. The database wallet is missing required files."),
    dbinject("GetVectorStoreCredentials",
             "Wallet-based DB connection failure signal",
             "Database connection failed. Unable to connect to the Knowledge Base database using the provided wallet"),
    noop("GetVectorStoreCredentials",
         "No connection verification invoked",
         "Resource returns credentials after building them."),
    dbinject("GetVectorStoreCredentials",
             "Embedding model does not exist (ORA-40284)",
             SUB_EMBEDDING),
    validation("GetVectorStoreCredentials",
               "Invalid request signal reaches classifier",
               "GET", "/knowledgeBases/{kb_key}/vectorStoreCredentials",
               [{"name": "wildcards", "path_params": {"kb_key": "***"}}],
               msg=SUB_INVALID_GENERIC, param_filled=False),
    race("GetVectorStoreCredentials",
         "Get vector store credentials times out",
         "Operation timed out. Getting vector store credentials did not complete in time."),
    infra("GetVectorStoreCredentials",
          "Other dependency failure",
          "Service unavailable. Failed to retrieve vector store credentials."),
])

print("\nDone.")
